version: '3'
services:
  weby:
    # replace username/repo:tag with your name and image details
    image: xergioalex/friendlyhello:demo
    deploy:
      replicas: 6
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "3000:80"
    networks:
      - webnet

networks:
  webnet:
    driver: overlay